# 借 RinLit 的 ci 来抄抄，他应该不会介意罢（
[changelog]
body = """

## Plugin Update Log
> [!NOTE]
> New Version: `{% if version %}({{ version }}){%- endif -%}`

{% for group, commits in commits | group_by(attribute="group") %}

{% if group != "New Feature" %}
<details>
<summary><h3>{{ group | upper_first }}</h3></summary>
{% for commit in commits | unique(attribute="message") %}
- {% if commit.scope %}{{ commit.scope }}: {%- endif -%}{{ commit.message | upper_first }}\
  {% if commit.remote.username %} Author: @{{ commit.remote.username }}{%- endif -%}
{% endfor %}
</details>
{% else %}
### {{ group | upper_first }}
{% for commit in commits | unique(attribute="message") %}
- {% if commit.scope %}{{ commit.scope }}: {%- endif -%}{{ commit.message | upper_first }}\
  {% if commit.remote.username %} Author: @{{ commit.remote.username }}{%- endif -%}
{% endfor %}
{% endif %}

{% endfor -%}

{% if version %}
  {% if previous.version %}
**Changelog**: {{ previous.version }} → {{ version }}
  {% endif %}
{% else -%}
  {% raw %}
{% endraw %}
{% endif %}

"""
trim = true
footer = "<!-- generated by git-cliff -->"
output = "CHANGELOG.md"


[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat", group = "New Feature"},
    { message = "^fix", group = "Bug Fix"},
    { message = "^refactor", group = "Refactor"},
    { message = "^docs", group = "Documentation"},
    { message = "^style", group = "Style"},
]
protect_breaking_commits = false
filter_commits = true
topo_order = false
sort_commits = "oldest"
link_parsers = []